# Build the manager binary
FROM golang:1.13 as builder

WORKDIR /workspace
COPY lib/ lib/

WORKDIR controller

# Copy the Go Modules manifests
COPY controller/go.mod go.mod
COPY controller/go.sum go.sum

RUN go mod download

# Copy the go source
COPY controller/main.go main.go
COPY controller/api/ api/
COPY controller/controllers/ controllers/
COPY controller/util/ util/

COPY controller/resources/ resources/

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/controller/manager .
COPY --from=builder /workspace/controller/resources /resources
USER nonroot:nonroot

ENTRYPOINT ["/manager"]
