/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class V1alpha1ApplicationSpecVolumes {
    /**
    * the path we use to mount this volume to container
    */
    'path': string;
    /**
    * use to store pvc name, so the disk won\'t be recreate during restart This field also can be used with existing pvc
    */
    'persistentVolumeClaimName'?: string;
    /**
    * If we need to create this volume first, the size of the volume
    */
    'size': string;
    /**
    * Identify the StorageClass to create the pvc
    */
    'storageClassName'?: string;
    /**
    * Volume type
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "persistentVolumeClaimName",
            "baseName": "persistentVolumeClaimName",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "string"
        },
        {
            "name": "storageClassName",
            "baseName": "storageClassName",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpecVolumes.attributeTypeMap;
    }
}

