/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class V1alpha1ApplicationSpecPorts {
    'containerPort': number;
    'name': string;
    /**
    * Protocol defines network protocols supported for things like container ports.
    */
    'protocol'?: ProtocolEnum;
    /**
    * port for service
    */
    'servicePort'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "containerPort",
            "baseName": "containerPort",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "protocol",
            "baseName": "protocol",
            "type": "ProtocolEnum"
        },
        {
            "name": "servicePort",
            "baseName": "servicePort",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpecPorts.attributeTypeMap;
    }
}


export enum ProtocolEnum {
        TCP = 'TCP',
        UDP = 'UDP',
        SCTP = 'SCTP'
    }