/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ApplicationStatusServiceStatusLoadBalancerIngress } from './v1alpha1ApplicationStatusServiceStatusLoadBalancerIngress';

/**
* LoadBalancer contains the current status of the load-balancer, if one is present.
*/
export class V1alpha1ApplicationStatusServiceStatusLoadBalancer {
    /**
    * Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points.
    */
    'ingress'?: Array<V1alpha1ApplicationStatusServiceStatusLoadBalancerIngress>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ingress",
            "baseName": "ingress",
            "type": "Array<V1alpha1ApplicationStatusServiceStatusLoadBalancerIngress>"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationStatusServiceStatusLoadBalancer.attributeTypeMap;
    }
}

