/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ObjectMeta } from "../model/models";
import { V1alpha1FileSpec } from "./v1alpha1FileSpec";

/**
 * File is the Schema for the files API
 */
export class V1alpha1File {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  "apiVersion"?: string;
  "data": string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  "kind"?: string;
  "metadata"?: V1ObjectMeta;
  /**
   * FileStatus defines the observed state of File
   */
  "spec"?: V1alpha1FileSpec;
  "status"?: object;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: "apiVersion",
      baseName: "apiVersion",
      type: "string"
    },
    {
      name: "data",
      baseName: "data",
      type: "string"
    },
    {
      name: "kind",
      baseName: "kind",
      type: "string"
    },
    {
      name: "metadata",
      baseName: "metadata",
      type: "object"
    },
    {
      name: "status",
      baseName: "status",
      type: "object"
    },
    {
      name: "spec",
      baseName: "spec",
      type: "V1alpha1FileSpec"
    }
  ];

  static getAttributeTypeMap() {
    return V1alpha1File.attributeTypeMap;
  }
}
