/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ApplicationStatusComponentStatus } from './v1alpha1ApplicationStatusComponentStatus';

/**
* ApplicationStatus defines the observed state of Application
*/
export class V1alpha1ApplicationStatus {
    /**
    * Failed to use map here, so use array for now.
    */
    'componentStatus'?: Array<V1alpha1ApplicationStatusComponentStatus>;
    'isActive'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "componentStatus",
            "baseName": "componentStatus",
            "type": "Array<V1alpha1ApplicationStatusComponentStatus>"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationStatus.attributeTypeMap;
    }
}

