/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ApplicationSpecDownwardAPIFieldRef } from './v1alpha1ApplicationSpecDownwardAPIFieldRef';
import { V1alpha1ApplicationSpecDownwardAPIResourceFieldRef } from './v1alpha1ApplicationSpecDownwardAPIResourceFieldRef';

/**
* DownwardAPIVolumeFile represents information to create the file containing the pod field
*/
export class V1alpha1ApplicationSpecDownwardAPIItems {
    'fieldRef'?: V1alpha1ApplicationSpecDownwardAPIFieldRef;
    /**
    * Optional: mode bits to use on this file, must be a value between 0 and 0777. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
    */
    'mode'?: number;
    /**
    * Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the \'..\' path. Must be utf-8 encoded. The first item of the relative path must not start with \'..\'
    */
    'path': string;
    'resourceFieldRef'?: V1alpha1ApplicationSpecDownwardAPIResourceFieldRef;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fieldRef",
            "baseName": "fieldRef",
            "type": "V1alpha1ApplicationSpecDownwardAPIFieldRef"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "number"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "resourceFieldRef",
            "baseName": "resourceFieldRef",
            "type": "V1alpha1ApplicationSpecDownwardAPIResourceFieldRef"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpecDownwardAPIItems.attributeTypeMap;
    }
}

