/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ApplicationSpecDownwardAPIItems } from './v1alpha1ApplicationSpecDownwardAPIItems';

/**
* information about the downwardAPI data to project
*/
export class V1alpha1ApplicationSpecProjectedDownwardAPI {
    /**
    * Items is a list of DownwardAPIVolume file
    */
    'items'?: Array<V1alpha1ApplicationSpecDownwardAPIItems>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<V1alpha1ApplicationSpecDownwardAPIItems>"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpecProjectedDownwardAPI.attributeTypeMap;
    }
}

