/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ApplicationSpecEnv } from './v1alpha1ApplicationSpecEnv';
import { V1alpha1ApplicationSpecLivenessProbe } from './v1alpha1ApplicationSpecLivenessProbe';
import { V1alpha1ApplicationSpecPorts } from './v1alpha1ApplicationSpecPorts';
import { V1alpha1ApplicationSpecVolumeMounts } from './v1alpha1ApplicationSpecVolumeMounts';

export class V1alpha1ApplicationSpecComponents {
    'afterStart'?: Array<string>;
    'args'?: Array<string>;
    'beforeDestroy'?: Array<string>;
    'beforeStart'?: Array<string>;
    'command'?: Array<string>;
    'cpu'?: string;
    'env'?: Array<V1alpha1ApplicationSpecEnv>;
    'image': string;
    'livenessProbe'?: V1alpha1ApplicationSpecLivenessProbe;
    'memory'?: string;
    'name': string;
    'plugins'?: Array<object>;
    'ports'?: Array<V1alpha1ApplicationSpecPorts>;
    'readinessProbe'?: V1alpha1ApplicationSpecLivenessProbe;
    'type'?: TypeEnum;
    'volumeMounts'?: Array<V1alpha1ApplicationSpecVolumeMounts>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "afterStart",
            "baseName": "afterStart",
            "type": "Array<string>"
        },
        {
            "name": "args",
            "baseName": "args",
            "type": "Array<string>"
        },
        {
            "name": "beforeDestroy",
            "baseName": "beforeDestroy",
            "type": "Array<string>"
        },
        {
            "name": "beforeStart",
            "baseName": "beforeStart",
            "type": "Array<string>"
        },
        {
            "name": "command",
            "baseName": "command",
            "type": "Array<string>"
        },
        {
            "name": "cpu",
            "baseName": "cpu",
            "type": "string"
        },
        {
            "name": "env",
            "baseName": "env",
            "type": "Array<V1alpha1ApplicationSpecEnv>"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "livenessProbe",
            "baseName": "livenessProbe",
            "type": "V1alpha1ApplicationSpecLivenessProbe"
        },
        {
            "name": "memory",
            "baseName": "memory",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "plugins",
            "baseName": "plugins",
            "type": "Array<object>"
        },
        {
            "name": "ports",
            "baseName": "ports",
            "type": "Array<V1alpha1ApplicationSpecPorts>"
        },
        {
            "name": "readinessProbe",
            "baseName": "readinessProbe",
            "type": "V1alpha1ApplicationSpecLivenessProbe"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TypeEnum"
        },
        {
            "name": "volumeMounts",
            "baseName": "volumeMounts",
            "type": "Array<V1alpha1ApplicationSpecVolumeMounts>"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpecComponents.attributeTypeMap;
    }
}


export enum TypeEnum {
        Server = 'Server',
        Cronjob = 'Cronjob'
    }