/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ApplicationSpecProjectedConfigMap } from './v1alpha1ApplicationSpecProjectedConfigMap';
import { V1alpha1ApplicationSpecProjectedDownwardAPI } from './v1alpha1ApplicationSpecProjectedDownwardAPI';
import { V1alpha1ApplicationSpecProjectedSecret } from './v1alpha1ApplicationSpecProjectedSecret';
import { V1alpha1ApplicationSpecProjectedServiceAccountToken } from './v1alpha1ApplicationSpecProjectedServiceAccountToken';

/**
* Projection that may be projected along with other supported volume types
*/
export class V1alpha1ApplicationSpecProjectedSources {
    'configMap'?: V1alpha1ApplicationSpecProjectedConfigMap;
    'downwardAPI'?: V1alpha1ApplicationSpecProjectedDownwardAPI;
    'secret'?: V1alpha1ApplicationSpecProjectedSecret;
    'serviceAccountToken'?: V1alpha1ApplicationSpecProjectedServiceAccountToken;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "configMap",
            "baseName": "configMap",
            "type": "V1alpha1ApplicationSpecProjectedConfigMap"
        },
        {
            "name": "downwardAPI",
            "baseName": "downwardAPI",
            "type": "V1alpha1ApplicationSpecProjectedDownwardAPI"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "V1alpha1ApplicationSpecProjectedSecret"
        },
        {
            "name": "serviceAccountToken",
            "baseName": "serviceAccountToken",
            "type": "V1alpha1ApplicationSpecProjectedServiceAccountToken"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpecProjectedSources.attributeTypeMap;
    }
}

