/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Flocker represents a Flocker volume attached to a kubelet\'s host machine. This depends on the Flocker control service being running
*/
export class V1alpha1ApplicationSpecFlocker {
    /**
    * Name of the dataset stored as metadata -> name on the dataset for Flocker should be considered as deprecated
    */
    'datasetName'?: string;
    /**
    * UUID of the dataset. This is unique identifier of a Flocker dataset
    */
    'datasetUUID'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "datasetName",
            "baseName": "datasetName",
            "type": "string"
        },
        {
            "name": "datasetUUID",
            "baseName": "datasetUUID",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpecFlocker.attributeTypeMap;
    }
}

