/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ApplicationSpecCsiNodePublishSecretRef } from './v1alpha1ApplicationSpecCsiNodePublishSecretRef';

/**
* CSI (Container Storage Interface) represents storage that is handled by an external CSI driver (Alpha feature).
*/
export class V1alpha1ApplicationSpecCsi {
    /**
    * Driver is the name of the CSI driver that handles this volume. Consult with your admin for the correct name as registered in the cluster.
    */
    'driver': string;
    /**
    * Filesystem type to mount. Ex. \"ext4\", \"xfs\", \"ntfs\". If not provided, the empty value is passed to the associated CSI driver which will determine the default filesystem to apply.
    */
    'fsType'?: string;
    'nodePublishSecretRef'?: V1alpha1ApplicationSpecCsiNodePublishSecretRef;
    /**
    * Specifies a read-only configuration for the volume. Defaults to false (read/write).
    */
    'readOnly'?: boolean;
    /**
    * VolumeAttributes stores driver-specific properties that are passed to the CSI driver. Consult your driver\'s documentation for supported values.
    */
    'volumeAttributes'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "driver",
            "baseName": "driver",
            "type": "string"
        },
        {
            "name": "fsType",
            "baseName": "fsType",
            "type": "string"
        },
        {
            "name": "nodePublishSecretRef",
            "baseName": "nodePublishSecretRef",
            "type": "V1alpha1ApplicationSpecCsiNodePublishSecretRef"
        },
        {
            "name": "readOnly",
            "baseName": "readOnly",
            "type": "boolean"
        },
        {
            "name": "volumeAttributes",
            "baseName": "volumeAttributes",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpecCsi.attributeTypeMap;
    }
}

