/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, requests.cpu and requests.memory) are currently supported.
*/
export class V1alpha1ApplicationSpecDownwardAPIResourceFieldRef {
    /**
    * Container name: required for volumes, optional for env vars
    */
    'containerName'?: string;
    /**
    * Specifies the output format of the exposed resources, defaults to \"1\"
    */
    'divisor'?: string;
    /**
    * Required: resource to select
    */
    'resource': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "containerName",
            "baseName": "containerName",
            "type": "string"
        },
        {
            "name": "divisor",
            "baseName": "divisor",
            "type": "string"
        },
        {
            "name": "resource",
            "baseName": "resource",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpecDownwardAPIResourceFieldRef.attributeTypeMap;
    }
}

