/**
 * Kapp Models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ApplicationSpecDownwardAPIItems } from './v1alpha1ApplicationSpecDownwardAPIItems';

/**
* DownwardAPI represents downward API about the pod that should populate this volume
*/
export class V1alpha1ApplicationSpecDownwardAPI {
    /**
    * Optional: mode bits to use on created files by default. Must be a value between 0 and 0777. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
    */
    'defaultMode'?: number;
    /**
    * Items is a list of downward API volume file
    */
    'items'?: Array<V1alpha1ApplicationSpecDownwardAPIItems>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "defaultMode",
            "baseName": "defaultMode",
            "type": "number"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<V1alpha1ApplicationSpecDownwardAPIItems>"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpecDownwardAPI.attributeTypeMap;
    }
}

