/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1FileSpec FileSpec defines the desired state of File
type V1alpha1FileSpec struct {
	Content string `json:"content"`
	Path string `json:"path"`
}
