/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationSpecLivenessProbeHttpGetHttpHeaders HTTPHeader describes a custom header to be used in HTTP probes
type V1alpha1ApplicationSpecLivenessProbeHttpGetHttpHeaders struct {
	// The header field name
	Name string `json:"name"`
	// The header field value
	Value string `json:"value"`
}
