/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationStatusServiceStatus ServiceStatus represents the current status of a service.
type V1alpha1ApplicationStatusServiceStatus struct {
	LoadBalancer V1alpha1ApplicationStatusServiceStatusLoadBalancer `json:"loadBalancer,omitempty"`
}
