/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1PluginSpec struct for V1alpha1PluginSpec
type V1alpha1PluginSpec struct {
	Properties map[string]interface{} `json:"properties,omitempty"`
	Type string `json:"type"`
}
