/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationStatusComponentStatus struct for V1alpha1ApplicationStatusComponentStatus
type V1alpha1ApplicationStatusComponentStatus struct {
	DeploymentStatus V1alpha1ApplicationStatusDeploymentStatus `json:"deploymentStatus,omitempty"`
	Name string `json:"name"`
	ServiceStatus V1alpha1ApplicationStatusServiceStatus `json:"serviceStatus,omitempty"`
}
