/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationSpecDisks struct for V1alpha1ApplicationSpecDisks
type V1alpha1ApplicationSpecDisks struct {
	Path string `json:"path"`
	Size string `json:"size"`
	Type string `json:"type,omitempty"`
}
