/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1DependencySpec DependencySpec defines the desired state of Dependency
type V1alpha1DependencySpec struct {
	Config map[string]string `json:"config,omitempty"`
	Type string `json:"type"`
	Version string `json:"version"`
}
