/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationSpecComponents struct for V1alpha1ApplicationSpecComponents
type V1alpha1ApplicationSpecComponents struct {
	AfterStart []string `json:"afterStart,omitempty"`
	Args []string `json:"args,omitempty"`
	BeforeDestroy []string `json:"beforeDestroy,omitempty"`
	BeforeStart []string `json:"beforeStart,omitempty"`
	Command []string `json:"command,omitempty"`
	Cpu string `json:"cpu,omitempty"`
	Dependencies []string `json:"dependencies,omitempty"`
	Disks []V1alpha1ApplicationSpecDisks `json:"disks,omitempty"`
	Env []V1alpha1ApplicationSpecEnv `json:"env,omitempty"`
	Image string `json:"image"`
	LivenessProbe V1alpha1ApplicationSpecLivenessProbe `json:"livenessProbe,omitempty"`
	Memory string `json:"memory,omitempty"`
	Name string `json:"name"`
	Plugins []map[string]interface{} `json:"plugins,omitempty"`
	Ports []V1alpha1ApplicationSpecPorts `json:"ports,omitempty"`
	ReadinessProbe V1alpha1ApplicationSpecLivenessProbe `json:"readinessProbe,omitempty"`
	Schedule string `json:"schedule,omitempty"`
	WorkloadType string `json:"workloadType,omitempty"`
}
