/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationSpec ApplicationSpec defines the desired state of Application
type V1alpha1ApplicationSpec struct {
	Components []V1alpha1ApplicationSpecComponents `json:"components"`
	ImagePullSecretName string `json:"imagePullSecretName,omitempty"`
	SharedEnv []V1alpha1ApplicationSpecEnv `json:"sharedEnv,omitempty"`
}
