/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1DependencyStatus DependencyStatus defines the observed state of Dependency
type V1alpha1DependencyStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \"make\" to regenerate code after modifying this file
	Status string `json:"status"`
}
