/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationStatus ApplicationStatus defines the observed state of Application
type V1alpha1ApplicationStatus struct {
	// Failed to use map here, so use array for now.
	ComponentStatus []V1alpha1ApplicationStatusComponentStatus `json:"componentStatus,omitempty"`
	IsActive bool `json:"isActive,omitempty"`
}
