/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationStatusServiceStatusLoadBalancer LoadBalancer contains the current status of the load-balancer, if one is present.
type V1alpha1ApplicationStatusServiceStatusLoadBalancer struct {
	// Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points.
	Ingress []V1alpha1ApplicationStatusServiceStatusLoadBalancerIngress `json:"ingress,omitempty"`
}
