/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationSpecPorts struct for V1alpha1ApplicationSpecPorts
type V1alpha1ApplicationSpecPorts struct {
	ContainerPort int32 `json:"containerPort"`
	Name string `json:"name"`
	// Protocol defines network protocols supported for things like container ports.
	Protocol string `json:"protocol,omitempty"`
	// ? what is service port for?
	ServicePort int32 `json:"servicePort,omitempty"`
}
