/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationStatusServiceStatusLoadBalancerIngress LoadBalancerIngress represents the status of a load-balancer ingress point: traffic intended for the service should be sent to an ingress point.
type V1alpha1ApplicationStatusServiceStatusLoadBalancerIngress struct {
	// Hostname is set for load-balancer ingress points that are DNS based (typically AWS load-balancers)
	Hostname string `json:"hostname,omitempty"`
	// IP is set for load-balancer ingress points that are IP based (typically GCE or OpenStack load-balancers)
	Ip string `json:"ip,omitempty"`
}
