/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
import (
	"time"
)
// V1alpha1ApplicationStatusDeploymentStatusConditions DeploymentCondition describes the state of a deployment at a certain point.
type V1alpha1ApplicationStatusDeploymentStatusConditions struct {
	// Last time the condition transitioned from one status to another.
	LastTransitionTime time.Time `json:"lastTransitionTime,omitempty"`
	// The last time this condition was updated.
	LastUpdateTime time.Time `json:"lastUpdateTime,omitempty"`
	// A human readable message indicating details about the transition.
	Message string `json:"message,omitempty"`
	// The reason for the condition's last transition.
	Reason string `json:"reason,omitempty"`
	// Status of the condition, one of True, False, Unknown.
	Status string `json:"status"`
	// Type of deployment condition.
	Type string `json:"type"`
}
