/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ComponentTemplateSpecEnv struct for V1alpha1ComponentTemplateSpecEnv
type V1alpha1ComponentTemplateSpecEnv struct {
	Name string `json:"name"`
	Type string `json:"type"`
	Value string `json:"value,omitempty"`
}
