/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ComponentTemplateSpec ComponentTemplateSpec defines the desired state of ComponentTemplate
type V1alpha1ComponentTemplateSpec struct {
	AfterStart []string `json:"afterStart,omitempty"`
	Args []string `json:"args,omitempty"`
	BeforeDestroy []string `json:"beforeDestroy,omitempty"`
	BeforeStart []string `json:"beforeStart,omitempty"`
	Command []string `json:"command,omitempty"`
	Cpu string `json:"cpu,omitempty"`
	Env []V1alpha1ComponentTemplateSpecEnv `json:"env,omitempty"`
	Image string `json:"image"`
	Memory string `json:"memory,omitempty"`
	Name string `json:"name"`
	Ports []V1alpha1ApplicationSpecPorts `json:"ports,omitempty"`
	Schedule string `json:"schedule,omitempty"`
	VolumeMounts []V1alpha1ComponentTemplateSpecVolumeMounts `json:"volumeMounts,omitempty"`
	WorkloadType string `json:"workloadType,omitempty"`
}
