/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationSpecLivenessProbeHttpGet HTTPGet specifies the http request to perform.
type V1alpha1ApplicationSpecLivenessProbeHttpGet struct {
	// Host name to connect to, defaults to the pod IP. You probably want to set \"Host\" in httpHeaders instead.
	Host string `json:"host,omitempty"`
	// Custom headers to set in the request. HTTP allows repeated headers.
	HttpHeaders []V1alpha1ApplicationSpecLivenessProbeHttpGetHttpHeaders `json:"httpHeaders,omitempty"`
	// Path to access on the HTTP server.
	Path string `json:"path,omitempty"`
	// Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
	Port map[string]interface{} `json:"port"`
	// Scheme to use for connecting to the host. Defaults to HTTP.
	Scheme string `json:"scheme,omitempty"`
}
