/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1FileStatus struct for V1alpha1FileStatus
type V1alpha1FileStatus struct {
	LastPath string `json:"lastPath,omitempty"`
}
