/*
 * Kapp Models
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kappmodel
// V1alpha1ApplicationSpecEnv EnvVar represents an environment variable present in a Container.
type V1alpha1ApplicationSpecEnv struct {
	// Name of the environment variable. Must be a C_IDENTIFIER.
	Name string `json:"name"`
	Prefix string `json:"prefix,omitempty"`
	Suffix string `json:"suffix,omitempty"`
	Type string `json:"type,omitempty"`
	Value string `json:"value,omitempty"`
}
